repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      exclude: ^migrations/

-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      exclude: ^tests/
      args: [ --config, pyproject.toml ]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: ^migrations/
      args: [--config, setup.cfg]

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.931
#    hooks:
#      - id: mypy
#        exclude: ^migrations/
#        args: [--config, setup.cfg]
