"""lol

Revision ID: 254ae2b3f6b8
Revises: 
Create Date: 2022-06-02 11:48:02.161924

"""
import sqlalchemy as sa
import sqlmodel  # NEW
from alembic import op

# revision identifiers, used by Alembic.
revision = "254ae2b3f6b8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run",
        sa.Column("os", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("commit_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("commit_time", sa.DateTime(), nullable=False),
        sa.Column("client_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_environment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metric",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric")
    op.drop_table("run")
    # ### end Alembic commands ###
